name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has had no activity in the last 60 days. Will be automatically close if this continues.'
        stale-pr-message: 'This PR has had no activity in the last 60 days. Will be automatically close if this continues.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
