name: Yaml Lint
on: [pull_request]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v1
      with:
        file_or_dir: plugins/*.*ml # check the plugins folder
        config_file: .yamlLint.yml
